### ISSUE TITLE
TypeResolver returns wrong anonymous type because of caching

### ISSUE THREAD

**Issue by azabluda** [6bee/aqua-core#6]
We observe one peculiar and fairly unstable bug in `TypeResolver` for which I think I found an explanation.

Apparently under certain conditions the runtime generates anonymous types with the same name `<>f__AnonymousType0´2` but different `DeclaringAssembly` and different sets of properties. Exactly for such cases the `TypeResolver.IsValid` method contains the intelligent distinction logic based on matching property names.

The problem occurs when the first candidate is successfully resolved and cached in `TypeResolver._typeCache`. Then the second candidate is fetched from the cache bypassing the `TypeResolver.IsValid` method simply because the class names are identical.

It's a bit problematic to provide simple test, but I hope my explanation is clear.

**Comment by 6bee** [comment]
Do you mean using `DeclaringAssembly` for additional equality comparison for caching would eliminate the issue?

**Comment by azabluda** [comment]
Might work, but AFAIK `DeclaringAssembly` is not part of `Aqua.TypeSystem.TypeInfo`. Adding this property may affect backward compatibility and increase the size of serialized telegrams. Furthermore it still feels a bit inconsistent to use `DeclaringAssembly` for matching items in the cache but rely on `propertyNames.All(x => properties.Contains(x))` in `TypeInfo.IsValid` method.

I could suggest extracting the property name matching logic for anonymous types and reusing it in both scenarios. This may have a certain impact on the performance of `TypeInfo.Equals / GetHashCode` though...

Just out of curiosity, apparently you ran into a real situation some time in the past which forced you to implement the property matching logic. Do you remember what was it exactly? Can't this case be isolated and covered by unit tests?

**Comment by 6bee** [comment]
As far as I remember, the reason for having a check on property names was to be able to distinguish types, originating from different clients, sending type information to a shared web service.

**Comment by 6bee** [comment]
Although applying the logic comparing property names (as done in IsValid) could be done specifically for the cache, I would suggest it should actually be included in TypeInfo.Equals but not necessarily in GetHashCode.

**Comment by azabluda** [comment]
To be quite honest I never was a big fan of overloaded Equals/GetHashCode, because every change of the custom implementation has a global and hardly traceable scope. Your suggestion should solve the problem, also I don't expect any side-effects in _our_ project, but (!) we can not be certain there exist no _other programs_ relying on the old behavior of Equals. So yeah, basically green light from my side.

As for your shared web service scenario, I see it isn't so easy to isolate it into a small unit test. As an idea I could suggest creating two tiny assemblies (perhaps even [dynamic ones](https://msdn.microsoft.com/en-us/library/saf5ce06(v=vs.110).aspx)?) with trivial methods
```c#
// in assembly 1
public static object CreateAnonymousObject1()
{
  return new { Foo = 1 };
}

// in assembly 2
public static object CreateAnonymousObject2()
{
  return new { Bar = "hello" };
}
```
and see if they both return `<>f__AnonymousType0´1`.

P.S: less accurate yet faster `GetHashCode` is an interesting compromise, will compute the same hash for all anonymous types of the same number of properties forcing a linear search in a hash table.

**Comment by 6bee** [comment]
Your point on overloaded Equals/GetHashCode is convincing. I've implemented a separate EqualityComparer instead. See commit 0883777

**Comment by azabluda** [comment]
Awesome commit, thank you! I especially like the thorough test coverage. Looking forward to seeing how it all works in the next release.

**Comment by azabluda** [comment]
After installing 4.0.0-alpha-038 we observed a major performance loss. We have over 1000 unit tests which normally complete within a minute, but now the speed is going down exponentially and after 300-400 tests the progress bar is practically not moving anymore.

The profiler hints to the new equality comparer in the `TypeResolver`, so I took a closer look at it. The dictionary contains about 300 entries but most of `Keys` have zero hash code, even for simplest types like `Int32`.

```
$1.Keys.Select(x => new { hash = $1.Comparer.GetHashCode(x), type = x.ToString() }).ToList()

    [0]: {{ hash = 0, type = Employee }}
    [1]: {{ hash = 0, type = System.Int32 }}
    [2]: {{ hash = 0, type = Remote.Linq.VariableQueryArgument`1[System.Int32] }}
    [3]: {{ hash = 0, type = System.Nullable`1[System.Int32] }}
    [4]: {{ hash = 0, type = Remote.Linq.DynamicQuery.QueryableResourceDescriptor }}
    [5]: {{ hash = 0, type = System.String }}
    [6]: {{ hash = 0, type = Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[Employee] }}
    [7]: {{ hash = 0, type = System.Linq.Queryable }}
    [8]: {{ hash = 0, type = System.Linq.IQueryable`1[Employee] }}
    [9]: {{ hash = 0, type = System.Boolean }}
    [10]: {{ hash = 0, type = System.Func`2[Employee,System.Boolean] }}
    [11]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Employee,System.Boolean]] }}
    [12]: {{ hash = 0, type = Microsoft.EntityFrameworkCore.EF }}
    [13]: {{ hash = 0, type = System.Object }}
    [14]: {{ hash = 0, type = System.Func`2[Employee,System.Nullable`1[System.Int32]] }}
    [15]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Employee,System.Nullable`1[System.Int32]]] }}
    [16]: {{ hash = 0, type = System.Linq.IQueryable`1[System.Nullable`1[System.Int32]] }}
    [17]: {{ hash = 0, type = Remote.Linq.VariableQueryArgument`1[System.String] }}
    [18]: {{ hash = 0, type = Customer }}
    [19]: {{ hash = 0, type = Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[Customer] }}
    [20]: {{ hash = 0, type = System.Linq.IQueryable`1[Customer] }}
    [21]: {{ hash = 0, type = System.Func`2[Customer,System.Boolean] }}
    [22]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Customer,System.Boolean]] }}
    [23]: {{ hash = 0, type = System.Func`2[Customer,System.String] }}
    [24]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Customer,System.String]] }}
    [25]: {{ hash = 0, type = System.Linq.IQueryable`1[System.String] }}
    [26]: {{ hash = 0, type = System.Collections.Generic.IEnumerable`1[System.String] }}
    [27]: {{ hash = 0, type = Product }}
    [28]: {{ hash = 0, type = Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[Product] }}
    [29]: {{ hash = 0, type = System.Linq.IQueryable`1[Product] }}
    [30]: {{ hash = 0, type = System.Func`2[Product,System.Boolean] }}
    [31]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Product,System.Boolean]] }}
    [32]: {{ hash = 0, type = Order }}
    [33]: {{ hash = -1712979019, type = <>f__AnonymousType1`2[Customer,Order] }}
    [34]: {{ hash = 0, type = Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[Order] }}
    [35]: {{ hash = 0, type = System.Linq.IQueryable`1[Order] }}
    [36]: {{ hash = 0, type = System.Func`2[Order,System.Boolean] }}
    [37]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Order,System.Boolean]] }}
    [38]: {{ hash = 0, type = System.Collections.Generic.IEnumerable`1[Order] }}
    [39]: {{ hash = 0, type = System.Func`2[Customer,System.Collections.Generic.IEnumerable`1[Order]] }}
    [40]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Customer,System.Collections.Generic.IEnumerable`1[Order]]] }}
    [41]: {{ hash = 0, type = System.Func`3[Customer,Order,<>f__AnonymousType1`2[Customer,Order]] }}
    [42]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`3[Customer,Order,<>f__AnonymousType1`2[Customer,Order]]] }}
    [43]: {{ hash = 0, type = System.Linq.IQueryable`1[<>f__AnonymousType1`2[Customer,Order]] }}
    [44]: {{ hash = 0, type = System.Func`2[<>f__AnonymousType1`2[Customer,Order],System.Boolean] }}
    [45]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[<>f__AnonymousType1`2[Customer,Order],System.Boolean]] }}
    [46]: {{ hash = 335048795, type = <>f__AnonymousType49`2[System.String,System.Int32] }}
    [47]: {{ hash = 0, type = System.Func`2[<>f__AnonymousType1`2[Customer,Order],<>f__AnonymousType49`2[System.String,System.Int32]] }}
    [48]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[<>f__AnonymousType1`2[Customer,Order],<>f__AnonymousType49`2[System.String,System.Int32]]] }}
    [49]: {{ hash = 0, type = System.DateTime }}
    [50]: {{ hash = 0, type = Remote.Linq.VariableQueryArgument`1[System.Boolean] }}
    [51]: {{ hash = -302577047, type = <>f__AnonymousType13`1[System.Boolean] }}
    [52]: {{ hash = 0, type = System.Func`2[Customer,<>f__AnonymousType13`1[System.Boolean]] }}
    [53]: {{ hash = 0, type = System.Linq.Expressions.Expression`1[System.Func`2[Customer,<>f__AnonymousType13`1[System.Boolean]]] }}
    [54]: {{ hash = 0, type = System.String[] }}
    [55]: {{ hash = 0, type = Remote.Linq.VariableQueryArgument`1[System.String[]] }}
    [56]: {{ hash = 0, type = System.Collections.Generic.List`1[System.String] }}
    [57]: {{ hash = 0, type = Remote.Linq.VariableQueryArgument`1[System.Collections.Generic.List`1[System.String]] }}
    [58]: {{ hash = 0, type = System.Linq.Enumerable }}
    [59]: {{ hash = 0, type = System.Int64 }}
    ...
    etc.
```

I suggest to add a pair of round brackets for the last term
```c#
public int GetHashCode(TypeInfo obj)
{
    if (ReferenceEquals(null, obj))
    {
        return 0;
    }

    return (obj.ToString().GetHashCode() * 397)
        ^ (obj.Properties?.Select(x => x.Name).GetCollectionHashCode() ?? 0); // <<< HERE
}
```
and maybe a handful of unit tests.

**Comment by 6bee** [comment]
It's likely that performance is still not good enough since `GetHashCode` might already be to expensive due to `TypeInfo.ToString` involved.
Might add sort of caching for hashcodes in `TypeResolver.EqualityComparer` and use new instance in `TypeResolver.IsValid`…

**Comment by azabluda** [comment]
I rerun our tests with a locally patched version of aqua-core and the performance is back to normal.

**Comment by azabluda** [comment]
But there is one peculiar case when `TypeResolver` is still being confused by identically named anonymous types. Apparently when trying to resolve a generic type (e.g. `IEnumerable<>`) with anonymous generic argument it may still return the wrong entry from the cache because the property names are not checked.

Among other problems this leads to an error in `Aqua.TypeSystem.MethodInfo.ResolveMethod()`
```c#
namespace Aqua.Tests.TypeSystem.TypeResolver
{
    using System;
    using System.Collections.Generic;
    using Aqua.TypeSystem;
    using Shouldly;
    using System.Reflection;
    using Xunit;

    public class When_resolving_ienumerable_of_anonymous_type
    {
        public static void SayHello<T>(IEnumerable<T> param)
        {
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void ResolveMethod_should_return_original_method_info(bool dirtyCache)
        {
            var typeResolver = new TypeResolver();
            Type type1 = TestObjects1.Helper.GetAnonymousType1();
            Type type2 = TestObjects2.Helper.GetAnonymousType1();

            // "Pollute" the type cache
            if (dirtyCache)
            {
                typeResolver.ResolveType(
                    new Aqua.TypeSystem.TypeInfo(typeof(IEnumerable<>).MakeGenericType(type2)));
            }

            System.Reflection.MethodInfo methodInfo = this.GetType()
                .GetTypeInfo()
                .GetMethod(nameof(SayHello))
                .MakeGenericMethod(type1);

            System.Reflection.MethodInfo resolvedMethod =
                new Aqua.TypeSystem.MethodInfo(methodInfo).ResolveMethod(typeResolver);
            resolvedMethod.ShouldBe(methodInfo);
        }
    }
}
```
```
Result Message:	Sequence contains no elements

Result StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Aqua.TypeSystem.MethodInfo.ResolveMethod(ITypeResolver typeResolver) in D:\aqua-core\src\Aqua\TypeSystem\MethodInfo.cs:line 106
   at Aqua.Tests.TypeSystem.TypeResolver.When_resolving_ienumerable_of_anonymous_type.ResolveMethod_should_return_original_method_info(Boolean dirtyCache) in D:\aqua-core\test\Aqua.Tests\TypeSystem\TypeResolver\When_resolving_a_system_type.cs:line 39
```

**Comment by 6bee** [comment]
In commit 7f25251 we actually also got rid of `TypeInfo.ToString().GetHashCode()`, so I hope at least performance doesn't get worse...

**Comment by 6bee** [comment]
Resolved and deployed as `4.0.0-alpha-040`.
Feel free to reopen if required.
